### ISSUE TITLE
Improve package's doctests

### ISSUE THREAD

**Issue by bonjourmauko** [openfisca/openfisca-core#1061]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

```
pytest openfisca_core openfisca_web_api --maxfail 0 --continue-on-collection-errors --quiet
```

### Here is what I expected to happen:

```
XXX passed, X xfailed, XXX warnings in X.XXs
```

### Here is what actually happened:

```
========================================================================================= short test summary info ==========================================================================================
FAILED openfisca_core/commons/formulas.py::openfisca_core.commons.formulas.apply_thresholds
FAILED openfisca_core/commons/formulas.py::openfisca_core.commons.formulas.switch
FAILED openfisca_core/holders/holder.py::openfisca_core.holders.holder.Holder.get_memory_usage
...
ERROR openfisca_core/scripts/measure_numpy_condition_notations.py::test_switch_select
```

### Context:

Python provides `doctests` to help keep a testable documentation.

They provide some benefits:

- They help maintainers and contributors to spot bugs and improvement opportunities.
- They helps reusers to understand the code quickly
- They help separating contexts (unit, functional, ...)
- They help produce the [official doc](https://openfisca.org/doc)

### Complications:

Today the code coverage by doctests is mild, they are not run, and most of them are broken. 

Some observed consequences:

- The code is in overall hard to grasp without a consequent time investment, thus hard to contribute to
- The code is hard to test unitarily due to its current design
- There are then very few unit tests
- The documentation ~is~ was [broken](https://github.com/openfisca/openfisca-doc/issues/244)

### Proposal:

Fix, complete, and run doctests systematically!

### TODO

- [x] #1250
- [x] #1249
- [x] #1254 
- [ ] #1266
- [x] #1267
- [ ] #1268
- [ ] #1269
- [ ] #1276
- [ ] 9.  Improve `openfisca_core.projectors` doctests
- [ ] 10. Improve `openfisca_core.reforms` doctests
- [ ] 11. Improve `openfisca_core.simulation_builder` doctests
- [ ] 12. Improve `openfisca_core.simulations` doctests
- [ ] 13. Improve `openfisca_core.taxbenefitsystems` doctests
- [ ] 14. Improve `openfisca_core.taxscales` doctests
- [ ] 15. Improve `openfisca_core.tracers` doctests
- [ ] 16. Improve `openfisca_core.variables` doctests
- [ ] 17. Improve `openfisca_web_api.loader` doctests
