### ISSUE TITLE
Improve package's documentation

### ISSUE THREAD

**Issue by bonjourmauko** [openfisca/openfisca-core#1063]
Linked to #1002 

### Context:

Documentation helps reusers, and interested public in general, to quickly understand OpenFisca.

### Complications:

Documentation is either broken, outdated, and/or fairly incomplete.

### TODO

- [x] #1251
- [x] #1262
- [x] #1252
- [x] #1274
- [ ] #1270
- [x] #1271
- [ ] 6.  Improve `openfisca_core.parameters` documentation
- [ ] 7.  Improve `openfisca_core.periods` documentation
- [ ] #1277
- [ ] 9.  Improve `openfisca_core.projectors` documentation
- [ ] 10. Improve `openfisca_core.reforms` documentation
- [ ] 11. Improve `openfisca_core.simulation_builder` documentation
- [ ] 12. Improve `openfisca_core.simulations` documentation
- [ ] 13. Improve `openfisca_core.taxbenefitsystems` documentation
- [ ] 14. Improve `openfisca_core.taxscales` documentation
- [ ] 15. Improve `openfisca_core.tracers` documentation
- [ ] 16. Improve `openfisca_core.variables` documentation
- [ ] 17. Improve `openfisca_web_api.loader` documentation
