### ISSUE TITLE
Improved build/release workflow

### ISSUE THREAD

**Issue by bonjourmauko** [openfisca/openfisca-core#1259]
- [ ] Centralised all tasks in one task manager
- [ ] Updated the documentation
- [ ] Updated the CLI
