### ISSUE TITLE
Improve dependency management

### ISSUE THREAD

**Issue by bonjourmauko** [openfisca/openfisca-core#1260]
- [ ] Handled dependencies by context
- [ ] Programatically test for supported numpy versions
- [ ] Programatically test for supported python versions
- [ ] Fixed circular dependency core <> country/extension
- [ ] Run pip without the legacy resolver
