### ISSUE TITLE
Improve openfisca cli

### ISSUE THREAD

**Issue by bonjourmauko** [openfisca/openfisca-core#1309]
# Job story

When I'm working with an openfisca country package,
I need `openfisca test` to work as expected,
So to validate the work I'm doing

# TODO

- [ ] #1304
- [ ] Make the cli of openfisca test, testable
- [ ] Make the test runner of openfisca test more resilient
- [ ] Ensure that tracing `max_depth` works as expected with `country-template`
