### ISSUE TITLE
Update min versions to py310/np126 and max to py313/np211

### ISSUE THREAD

**Issue by bonjourmauko** [openfisca/openfisca-core#1314]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

I'm trying to work with openfisca with python version 3.12+ and numpy 2.0.2+, because they offer several improvements in terms of performance and new builtin syntax.

### Here is what I expected to happen:

To run `make` and for it to _just work_.

### Here is what actually happened:

I encounter several errors when installing such versions and then run `make`.

### TODO

- [ ] Update minimal Python version to 3.10
- [ ] Update maximal Python version to 3.12
- [ ] Update maximal Python version to 3.13
- [ ] Update minimal Numpy version to 1.26.x
- [ ] Update maximal Numpy version to 2.0.x
- [ ] Update maximal Numpy version to 2.1.x
