### ISSUE TITLE
Make openfisca-core compatible with Python 3

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-core#630]
From 1/1/2109 on NumPy won't be supporting Python 2.x anymore, so we'll probably have to move from 2.x to 3.x

**Definition of done :**

Assessment of general complexity and efforts to do this, and best-effort enumeration of things to do.

- [x] Foray 1 #631 
- [x] Foray 2 #632 
- [x] Make package compatible with Python 3.6 #660
- [x] Make package dependencies compatible with Python 3 openfisca/country-template#41
- [x] Automatic CI/CD #662 -> #666
- [ ] Performance assessment

Thanks for your information if you already have cc @fpagnoux and @benjello 

Should be compatible with 2.7 **and** 3.6

**Comment by fpagnoux** [comment]
What is the difference between Foray 1 and Foray 2 ?

I don't think moving to Python 3 will be a hard thing to do, but keeping compatibility with python 2 may be if we use python 3 specific features. 

What is the strategy about retro-compatibility ? Do we intend to keep OpenFisca compatible with Python 2 ? For how long ?

**Comment by benjello** [comment]
For the IPP, I think we can prepare to do a full switch to python 3 around next january (2019).
We can test it a bit locally during the summer but switching to python 3 on the CASD is risky and costly and we won't be able to do it in the summer or the autumn.

**Comment by fpagnoux** [comment]
> switching to python 3 on the CASD is risky and costly and we won't be able to do it in the summer or the autumn.

I'm suspecting that several of OpenFisca reusers will have the same issue. So I think OpenFisca will have to be compatible with Python 2 ou 3 for at least a couple of months.

To this aim, I'd suggest the following methodology:
- Try to run OpenFisca with python3
- Run into an issue
- Fix it in a way that works **both** for Python 2 and 3.
    - If there is a way of doing things that works for both version, I'd suggest using it instead of a more fancy python-3 way.
    - If we end up using new features brought by python3, polyfills (such as enum34) can be used
    - In the other case, and `if`/`else` block is always possible. 
    - In all case, the interface of OpenFisca should be the same in python 2 and 3.
- Move to the next issue 🚅 

I'd suggest _not_ to wait to have made the whole code python-3 compatible to start worrying about retro-compatibility. This strategy could lead to higher costs, as part of the work may need to be undone.

**Comment by maukoquiroga** [comment]
> What is the difference between Foray 1 and Foray 2 ?

As we can't foresee the efforts involved in the adoption of Python 3, a foray is a time-boxed exploration whose objective is to gain knowledge about what would it take to do it.

**Comment by fpagnoux** [comment]
Ok. I must say I'm slightly worried about issues like #632 and #631, with no clear deliverable and boundaries. Let's make sure it doesn't lead to work being done, not merged, and rotting in a stalen branch.
