### ISSUE TITLE
Improve usage statistics

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-core#685]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve usage statistics](https://trello.com/c/EsJCcILm/33-improve-usage-statistics)

**For** maintainers

**Story:**

When I'm prioritising which OpenFisca's evolutions to focus on,
I want to have actionable usage metrics at my disposal,
so I can decide which features to implement,
and so I can decide which features to deprecate,
and so I can decide which maintenance efforts to focus on.

**Definition of done :**

Have properly tracked visits/outlinks/events to make informed decisions.

To render [OpenFisca stats'](http://stats.data.gouv.fr/index.php?module=CoreHome&action=index&idSite=4&period=week&date=2018-07-08#?module=Dashboard&action=embeddedIndex&idSite=4&period=week&date=2018-07-08&idDashboard=1) exploitable, we need at least:

- [x] Make tracker compatible with Python 3 - parent openfisca/tracker#4
- [x] Track Web API version in Piwik stats - parent #594 
- [x] Nettoyer les statistiques Piwik - parent openfisca/openfisca-france#821
- [x] Visits not properly tracked in Piwik - parent openfisca/legislation-explorer#163
- [x] API visits not properly tracked in Piwik - parent openfisca/tracker#8
- [x] Track metadata in Piwik - parent #683

**Comment by maukoquiroga** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve usage statistics](https://trello.com/c/EsJCcILm/33-improve-usage-statistics)
